bt_navigator:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.05 # 2.864789 deg
      stateful: False
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      angular_dist_threshold: 0.1 # 5.72958 deg
      rotate_to_heading_angular_vel: 3.6
      max_angular_accel: 9.6

      desired_linear_vel: 1.0
      rotate_to_heading_min_angle: 0.5

lifecycle_manager:
  ros__parameters:
    autostart: true

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      static_layer:
        map_topic: <robot_namespace>/map
      obstacle_layer:
        observation_sources: scan
        scan:
          topic: <robot_namespace>/scanner1

global_costmap:
  global_costmap:
    ros__parameters:
      track_unknown_space: True
      robot_radius: 0.35 # 0.65
      static_layer:
        map_topic: <robot_namespace>/map
      obstacle_layer:
        observation_sources: scan
        scan:
          topic: <robot_namespace>/scanner1
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          raytrace_max_range: 7.0
          raytrace_min_range: 0.0
          obstacle_max_range: 5.0
          obstacle_min_range: 0.0
          inf_is_valid: false
      inflation_layer:
        inflation_radius: 1.0
        inflate_unknown: True
        inflate_around_unknown: False

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: True

planner_server:
  ros__parameters:
    use_sim_time: True
